name: Build and Deploy Node.js App

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/getting-started-app:latest

    - name: Stop existing container
      continue-on-error: true
      run: docker stop getting-started-app

    - name: Remove existing container
      continue-on-error: true
      run: docker rm getting-started-app

    - name: Pull and run new container
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/getting-started-app:latest
        docker run -d --name getting-started-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/getting-started-app:latest
        echo "Deployment complete!"