name: Build and Deploy Node.js App

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/getting-started:latest

    - name: Install cloudflared
      run: |
        curl -L --output cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        
    - name: Setup SSH config for Cloudflare Tunnel
      run: |
        $ssh_config_path = "$HOME\.ssh\config"
        $config_entry = @"
        Host ssh.kjoel.co.in
          ProxyCommand C:\actions-runner\_work\getting-started\getting-started\cloudflared.exe access ssh --hostname %h
        "@
        Add-Content -Path $ssh_config_path -Value $config_entry
        
    - name: Deploy to Server via Cloudflare Tunnel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} 
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Successfully connected to server via Cloudflare Tunnel!"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/getting-started:latest
          docker stop getting-started || true
          docker rm getting-started || true
          docker run -d --name getting-started -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/getting-started:latest
          echo "Deployment complete!"